### ISSUE TITLE
Breath of fire 3 save editor problem

### ISSUE THREAD

**Issue by spkpal** [glitch-in-the-herring/bof3-save-editor#4]
Hey

When i tried your Breath of fire 3 save editor on the ps1 duckstation, it keeps on saying file is damaged

and when i just tried your Breath of fire 3 save editor on the ps1 epsxe, it made my party member disappper

so what could be wrong then?

thanks

**Comment by glitch-in-the-herring** [comment]
Hello @spkpal 

What version of the game are you using? Can you tell me what you were modifying with the editor? Can you send an example of the broken save file?

**Comment by spkpal** [comment]
hey

this is what this 1 user said on the gamefaqs site about your breath of fire 3 save editor

TurretSyndrome (Topic Creator)1 month ago[#5](https://gamefaqs.gamespot.com/boards/196817-breath-of-fire-iii/80411912/973020619)
meth962 posted...

    I'm on the US version SLUS-00422BOF3
    I'm using ePSXe for mobile.
    It looks like the github editor can work for EU version as well. It only works with raw MC format save files though. (.mc, .mcr). Those are the files that start with 'MC' at the top of the file.


Thanks a lot for the information. I downloaded ePSXe for Windows and tried with that. You were right. .MCR files are the only ones that can be inputted and outputted.

If you use RetroArch or anything else which uses other save types like .MCD,
1) You will first have to create a save in .MCR format(meaning start your game in ePSXe and save)
2) Then, load that into the editor to make your changes
3) Load the edited file into ePSXe again and save for good measure
4) Change file type of the .MCR file to .MCD to be playable on RetroArch and the like.



About masters editing. Unfortunately, just enabling the masters and assigning them to the character in the editor will NOT imbue the character with the stat bonuses. You will also need to manually input the numbers for each stat for the character within the Stat Growth Modifier section on the editor. I'm not willing to do this as I don't want any unintended consequences with the stat bonuses some 20 hours into the game. However, I'm sure all other things work just fine like the stat changes etc.

Hope this helps anyone else who might want to use that editor.

I tried what that 1 user told me to do. but that did not work for me at all, because it still did not work for me at all

and i am using the USA version of breath of fire 3 on your save editor

and here is my broken save editor file

[epsxe000.zip](https://github.com/glitch-in-the-herring/bof3-save-editor/files/11769455/epsxe000.zip)

all i fixed up on your breath of fire 3 editor was changing my level to level 49

thanks

**Comment by spkpal** [comment]
I need this editor to be fixed please, i am not doing the fishing in this game at all

**Comment by spkpal** [comment]
I have no idea what i did wrong to break your editor on here

**Comment by glitch-in-the-herring** [comment]
@spkpal I did not have time to look into the issue yesterday, as I was busy at work. From a first glance however, it looks like the file that you sent me does not contain any save data.

**Comment by spkpal** [comment]
Hey Glitch-in-the-hearring

here is a youtube video showing the problem i had using your breath of fire 3 save editor

https://youtu.be/DS_smO5z2Sk

let me know if you need me to send you anymore details about this problem

do you think your Breath of fire 3 save editor broke on me because i did not have access to the menu at that part of the game, when kid ryu was still in his jammies?

if so i was thinking you could add in another warning message on your editor telling everyone not to use the editor at the very start of game until ryu in his armor

thanks

**Comment by glitch-in-the-herring** [comment]
Child Ryu wearing pyjamas wasn't listed in the party editor, which caused the bug. Commit a731dfd fixes this.
