### ISSUE TITLE
Hey there! Fishing issue.

### ISSUE THREAD

**Issue by junkyard-dave** [glitch-in-the-herring/bof3-save-editor#6]
I was trying to edit the fish to be 0 again (presuming that's even possible) based on new file and not catching them again, so, sorry first of all if this isn't supported and not a bug.

Provided you can zero out the fishing stats to make them appear as "???" again in fishing spots, it doesn't seem to save for me when I edit fish data. I can seemingly edit everything else, but the fish data. Thanks!

**Comment by glitch-in-the-herring** [comment]
Yeah, this isn't supposed to happen. I'll write a fix.

**Comment by glitch-in-the-herring** [comment]
fe399c99190acfbc4884c3c58dfa3adcdecc78a8 should resolve this. Let me know if anything breaks.
