### ISSUE TITLE
Garr's Beast Spear gets stolen after using editor and can't be hacked back in.

### ISSUE THREAD

**Issue by EmeraldEyesEsoteric** [glitch-in-the-herring/bof3-save-editor#7]
After the fight between Ryu and Gaist on the cliff past the save caves, you examine his corpse to find the Beast Spear, Garr's best weapon. It's 150 power, and has an inherent drain life ability. This was gone after using the editor. Now I can't get back his best weapon. Sure, I can buff his power, hp, and defense, but if someone uses an ability that drops his hp to 1 and he is attacking, there is no way to compensate for the loss of the spear's drain life move. Please Add this item to the editor, and double check to make sure you aren't missing any more items.

**Comment by glitch-in-the-herring** [comment]
Fixed inn 1bf6a8c7f9eba6ea28bcf196334195d41b693ebe
